// The Parameters can be Generated by the helper/guiFiles/generate.js!
#pragma once

#include <string>
#include <UIFiles.h>

#define UI_FILES_COUNT $d$
namespace VeNo::GUI {

struct preDefinedBinary {
  std::string name;
  const char* data;
};

struct Files {
  static preDefinedBinary preDefinedBinaries[UI_FILES_COUNT];
};
} // namespace VeNo::GUI