// The Parameters can be Generated by the helper/guiFiles/generate.js!
#pragma once

#include <UIFiles.h>
#include <string>

#define UI_FILES_COUNT 6
namespace VeNo::GUI {

struct preDefinedBinary {
  std::string name;
  const char *data;
};

struct Files {
  static preDefinedBinary preDefinedBinaries[UI_FILES_COUNT];
};
} // namespace VeNo::GUI