// The Parameters can be Generated by the helper/guiFiles/generate.js!
#pragma once

#include <string>
namespace VeNo::GUI {
struct Files {
  static std::string EMPTY;
  static std::string MainGui;
  static std::string OSC;
  static std::string WaveEditor;
  static std::string Footer;
  static std::string Sidebar;
};
} // namespace VeNo::GUI