// The Parameters can be Generated by the helper/parameter/parameterToCPP.js!
// Any Changes here also Provide to parameter.json
#include <VeNo/Core/Parameter/Handler.h>
#include <VeNo/Core/Parameter/Parameter.h>

namespace VeNo::Core {
void ParameterHandler::setupParameter () {
$s$
}
} // namespace VeNo::Core